### ISSUE TITLE
New Update throws error, will not allow auto-issue-creation

### ISSUE THREAD

**Issue by brettpoole** [Gert-dev/php-integrator-refactoring#23]
Steps to recreate issue:

1. Have previous version installed successfully
2. Update the package in Packages/Php Integrator Base
3. Go to open file.
4. Select code to refactor
5. Press [Alt]+m
6. See error trace (shown below)
7. Click "Create issue on the php-integrator-refactoring package"
8. Get "414 Request-URI Too Large" in the browser

```
Uncaught TypeError: Cannot read property 'storeFocusedElement' of null
/Users/brett/.atom/packages/php-integrator-refactoring/lib/ExtractMethodProvider.coffee:122
Hide Stack Trace
TypeError: Cannot read property 'storeFocusedElement' of null
    at ExtractMethodProvider.module.exports.ExtractMethodProvider.executeCommand (/Users/brett/.atom/packages/php-integrator-refactoring/lib/ExtractMethodProvider.coffee:122:27)
    at atom-text-editor.atom.commands.add.php-integrator-refactoring:extract-method (/Users/brett/.atom/packages/php-integrator-refactoring/lib/ExtractMethodProvider.coffee:40:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

**Comment by brettpoole** [comment]
Note: This seems to have been resolved by a restart of the application.

With this in mind, would it be a good idea to present the user with the suggestion to close and reopen after installation?

**Comment by Gert-dev** [comment]
Hello. Glad to hear you got it solved. As a package author I have no control over the upgrade process whatsoever, I can only listen to the package being deactivated and activated. The bug you ran into seems to be an Atom package updating issue. The method where it failed comes from a third-party dependency that is installed by running `apm install` in the package folder (which is handled by Atom automatically during upgrading and installation). Unfortunately, it seems Atom sometimes either:
* Fails to run `apm install`.
* Somehow "forgets" to install some files or removes them after installation. I don't even understand how this is possible, but it has happened before that a single PHP file shipped with a version was not present on a user's hard drive after upgrading (the other changes were).
* Upgrades the package successfully, but keeps running old JavaScript code instead of detecting the changed CoffeeScript files and automatically recompiling them to JavaScript, resulting in various errors because old JavaScript code is trying to communicate with new PHP code.

However, I'm going to look into creating an issue template for the base package for users wishing to report an issue to ensure they tried these things before reporting an issue since there isn't really anything I can do about them from this package.
